### Word Embedding Techniques using Embedding Layer in Keras

In [39]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:
State 
Maha
Karnataka
MP
AP
UP
Mah    Kar   MP   AP
1        0     0    0
0         1    0     0
0          0   1     0
0         0     0    1
0        0      0    0

In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[5594, 2372, 9769, 6448], [5594, 2372, 9769, 4248], [5594, 6420, 9769, 9985], [5057, 8402, 9633, 6363, 6303], [5057, 8402, 9633, 6363, 9462], [6275, 5594, 1178, 9769, 5798], [3207, 9628, 7574, 6363]]


### Word Embedding Represntation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5594 2372 9769 6448]
 [   0    0    0    0 5594 2372 9769 4248]
 [   0    0    0    0 5594 6420 9769 9985]
 [   0    0    0 5057 8402 9633 6363 6303]
 [   0    0    0 5057 8402 9633 6363 9462]
 [   0    0    0 6275 5594 1178 9769 5798]
 [   0    0    0    0 3207 9628 7574 6363]]


In [9]:
dim=10


In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[ 3.57506536e-02  1.03422292e-02  2.55091451e-02  1.66750439e-02
    1.50660165e-02  6.27945736e-03 -2.42208131e-02  7.61045143e-03
   -1.30813941e-02  4.97610010e-02]
  [ 3.57506536e-02  1.03422292e-02  2.55091451e-02  1.66750439e-02
    1.50660165e-02  6.27945736e-03 -2.42208131e-02  7.61045143e-03
   -1.30813941e-02  4.97610010e-02]
  [ 3.57506536e-02  1.03422292e-02  2.55091451e-02  1.66750439e-02
    1.50660165e-02  6.27945736e-03 -2.42208131e-02  7.61045143e-03
   -1.30813941e-02  4.97610010e-02]
  [ 3.57506536e-02  1.03422292e-02  2.55091451e-02  1.66750439e-02
    1.50660165e-02  6.27945736e-03 -2.42208131e-02  7.61045143e-03
   -1.30813941e-02  4.97610010e-02]
  [-1.59035213e-02  3.23078781e-03  1.94034688e-02  3.83099429e-02
    4.83455509e-03  3.24887522e-02 -2.78486963e-02 -3.81960496e-02
    3.88441794e-02  2.77205147e-02]
  [-8.35968181e-03  1.91051029e-02 -4.57258932e-02 -4.64296453e-02
    2.80976407e-02  1.00444555e-02 -2.34103203e-02  2.43337192e-02
    6.80939108e-

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 5594, 2372, 9769, 6448])

In [14]:
print(model.predict(embedded_docs)[0])

[[ 3.57506536e-02  1.03422292e-02  2.55091451e-02  1.66750439e-02
   1.50660165e-02  6.27945736e-03 -2.42208131e-02  7.61045143e-03
  -1.30813941e-02  4.97610010e-02]
 [ 3.57506536e-02  1.03422292e-02  2.55091451e-02  1.66750439e-02
   1.50660165e-02  6.27945736e-03 -2.42208131e-02  7.61045143e-03
  -1.30813941e-02  4.97610010e-02]
 [ 3.57506536e-02  1.03422292e-02  2.55091451e-02  1.66750439e-02
   1.50660165e-02  6.27945736e-03 -2.42208131e-02  7.61045143e-03
  -1.30813941e-02  4.97610010e-02]
 [ 3.57506536e-02  1.03422292e-02  2.55091451e-02  1.66750439e-02
   1.50660165e-02  6.27945736e-03 -2.42208131e-02  7.61045143e-03
  -1.30813941e-02  4.97610010e-02]
 [-1.59035213e-02  3.23078781e-03  1.94034688e-02  3.83099429e-02
   4.83455509e-03  3.24887522e-02 -2.78486963e-02 -3.81960496e-02
   3.88441794e-02  2.77205147e-02]
 [-8.35968181e-03  1.91051029e-02 -4.57258932e-02 -4.64296453e-02
   2.80976407e-02  1.00444555e-02 -2.34103203e-02  2.43337192e-02
   6.80939108e-03  2.45071575e-03